export const fonts = [
    'American Typewriter',
    'American Typewriter Condensed Light',
    'American Typewriter Condensed',
    'American Typewriter Condensed,Bold',
    'American Typewriter Light',
    'American Typewriter,Bold',
    'AndaleMono',
    'Arial Narrow',
    'Arial Narrow,Bold',
    'Arial Narrow,BoldItalic',
    'Arial Narrow,Italic',
    'Arial Rounded MT,Bold',
    'Arial UnicodeMS',
    'Arial,BoldItalicMT',
    'Arial,BoldMT',
    'Arial,ItalicMT',
    'Arial-Black',
    'ArialMT',
    'Athelas,Bold',
    'Athelas,BoldItalic',
    'Athelas,Italic',
    'Athelas-Regular',
    'Avenir Next Condensed Demi,Bold',
    'Avenir Next Condensed Demi,BoldItalic',
    'Avenir Next Condensed Heavy',
    'Avenir Next Condensed Heavy,Italic',
    'Avenir Next Condensed Medium',
    'Avenir Next Condensed Medium,Italic',
    'Avenir Next Condensed Regular',
    'Avenir Next Condensed Ultra Light',
    'Avenir Next Condensed Ultra Light,Italic',
    'Avenir Next Condensed,Bold',
    'Avenir Next Condensed,BoldItalic',
    'Avenir Next Condensed,Italic',
    'Avenir Next Demi,Bold',
    'Avenir Next Demi,BoldItalic',
    'Avenir Next Heavy',
    'Avenir Next Heavy,Italic',
    'Avenir Next Medium',
    'Avenir Next Medium,Italic',
    'Avenir Next Regular',
    'Avenir Next Ultra Light',
    'Avenir Next Ultra Light,Italic',
    'Avenir Next,Bold',
    'Avenir Next,BoldItalic',
    'Avenir Next,Italic',
    'Avenir-Black',
    'Avenir-BlackOblique',
    'Avenir-Book',
    'Avenir-BookOblique',
    'Avenir-Heavy',
    'Avenir-HeavyOblique',
    'Avenir-Light',
    'Avenir-LightOblique',
    'Avenir-Medium',
    'Avenir-MediumOblique',
    'Avenir-Oblique',
    'Avenir-Roman',
    'Baskerville',
    'Baskerville,Bold',
    'Baskerville,BoldItalic',
    'Baskerville,Italic',
    'BigCaslon-Medium',
    'BrushScriptMT',
    'Chalkboard',
    'Chalkboard SE Light',
    'Chalkboard SE Regular',
    'Chalkboard SE,Bold',
    'Chalkboard,Bold',
    'Chalkduster',
    'CharcoalCY',
    'Charter Black,Italic',
    'Charter,Bold',
    'Charter,BoldItalic',
    'Charter,Italic',
    'Charter-Black',
    'Charter-Roman',
    'Cochin',
    'Cochin,Bold',
    'Cochin,BoldItalic',
    'Cochin,Italic',
    'Comic Sans MS,Bold',
    'ComicSansMS',
    'Copperplate',
    'Copperplate,Bold',
    'Copperplate-Light',
    'Courier',
    'Courier New,Bold',
    'Courier New,BoldItalic',
    'Courier New,Italic',
    'Courier,Bold',
    'Courier-Oblique',
    'CourierNewPSMT',
    'DIN Alternate,Bold',
    'DIN Condensed,Bold',
    'Didot',
    'Didot,Bold',
    'Didot,Italic',
    'Futura Medium,Italic',
    'Futura-CondensedMedium',
    'Futura-Medium',
    'Geneva',
    'GenevaCyr',
    'Georgia',
    'Georgia,Bold',
    'Georgia,BoldItalic',
    'Georgia,Italic',
    'Gill Sans',
    'Gill Sans Light,Italic',
    'Gill Sans,Bold',
    'Gill Sans,BoldItalic',
    'Gill Sans,UltraBold',
    'GillSans,Italic',
    'GillSans-Light',
    'Helvetica',
    'Helvetica CY,Bold',
    'Helvetica Neue',
    'Helvetica Neue Condensed Black',
    'Helvetica Neue Condensed,Bold',
    'Helvetica Neue Light',
    'Helvetica Neue Light,Italic',
    'Helvetica Neue Medium',
    'Helvetica Neue Medium,Italic',
    'Helvetica Neue Thin',
    'Helvetica Neue Thin,Italic',
    'Helvetica Neue UltraLight',
    'Helvetica Neue UltraLight,Italic',
    'Helvetica Neue,Bold',
    'Helvetica Neue,BoldItalic',
    'Helvetica Neue,Italic',
    'Helvetica,Bold',
    'Helvetica-Light',
    'Helvetica-LightOblique',
    'Helvetica-Oblique',
    'HelveticaCY-Oblique',
    'HelveticaCY-Plain',
    'Herculanum',
    'Hoefler Text Black,Italic',
    'Hoefler Text,Italic',
    'HoeflerText-Black',
    'HoeflerText-Ornaments',
    'HoeflerText-Regular',
    'Impact',
    'Iowan Old Style Black,Italic',
    'Iowan Old Style,Bold',
    'Iowan Old Style,BoldItalic',
    'Iowan Old Style,Italic',
    'IowanOldStyle-Black',
    'IowanOldStyle-Roman',
    'IowanOldStyle-Titling',
    'Lucida Grande',
    'Lucida Grande,Bold',
    'Marion,Bold',
    'Marion,Italic',
    'Marion-Regular',
    'Marker Felt Thin',
    'Marker Felt Wide',
    'Menlo,Bold',
    'Menlo,BoldItalic',
    'Menlo,Italic',
    'Menlo-Regular',
    'Monaco',
    'Noteworthy,Bold',
    'Noteworthy-Light',
    'Optima,Bold',
    'Optima,BoldItalic',
    'Optima,Italic',
    'Optima-ExtraBlack',
    'Optima-Regular',
    'PT Mono,Bold',
    'PT Sans Caption,Bold',
    'PT Sans Narrow,Bold',
    'PT Sans,Bold',
    'PT Sans,BoldItalic',
    'PT Sans,Italic',
    'PT Serif Caption,Italic',
    'PT Serif,Bold',
    'PT Serif,BoldItalic',
    'PT Serif,Italic',
    'PTMono-Regular',
    'PTSans-Caption',
    'PTSans-Narrow',
    'PTSans-Regular',
    'PTSerif-Caption',
    'PTSerif-Regular',
    'Palatino,Bold',
    'Palatino,BoldItalic',
    'Palatino,Italic',
    'Palatino-Roman',
    'Papyrus',
    'Papyrus-Condensed',
    'PlantagenetCherokee',
    'STBaoli-SC-Regular',
    'STYuanti-SC-Light',
    'STYuanti-SC-Regular',
    'SavoyeLetPlain',
    'Seravek',
    'Seravek ExtraLight, Italic',
    'Seravek Light,Italic',
    'Seravek Medium,Italic',
    'Seravek,Bold',
    'Seravek,BoldItalic',
    'Seravek,Italic',
    'Seravek-ExtraLight',
    'Seravek-Light',
    'Seravek-Medium',
    'Skia-Regular',
    'Skia-Regular_Black',
    'Skia-Regular_Black-Condensed',
    'Skia-Regular_Black-Extended',
    'Skia-Regular_Condensed',
    'Skia-Regular_Extended',
    'Skia-Regular_Light',
    'Skia-Regular_Light-Condensed',
    'Skia-Regular_Light-Extended',
    'Snell Roundhand,Bold',
    'SnellRoundhand',
    'SnellRoundhand-Black',
    'Superclarendon Black,Italic',
    'Superclarendon Light,Italic',
    'Superclarendon,Bold',
    'Superclarendon,BoldItalic',
    'Superclarendon,Italic',
    'Superclarendon-Black',
    'Superclarendon-Light',
    'Superclarendon-Regular',
    'Tahoma',
    'Tahoma,Bold',
    'Times New Roman,Bold',
    'Times New Roman,BoldItalic',
    'Times New Roman,Italic',
    'Times,Bold',
    'Times,BoldItalic',
    'Times,Italic',
    'Times-Roman',
    'TimesNewRomanPSMT',
    'Trebuchet MS,Bold',
    'Trebuchet MS,BoldItalic',
    'Trebuchet MS,Italic',
    'TrebuchetMS',
    'Verdana',
    'Verdana,Bold',
    'Verdana,BoldItalic',
    'Verdana,Italic',
    'Waseem',
    'WaseemLight',
    'Webdings',
    'Wingdings-Regular',
    'Wingdings2',
    'Wingdings3',
    'Yuanti SC,Bold',
    'YuppySC-Regular',
    'Zapf Dingbats',
    'Zapfino'
];